### PR TITLE
Long run restart fix

### LINKED ISSUE #1051: failure in ERS 3 month nocomp test
I am trying to create longer runs using the latest CTSM in NorESM configurations (with the latest CMEPS, CDEPS, etc). The following 2 tests fail restarts: 
ERS_Lm3.f45_f45_mg37.2000_DATM%GSWP3v1_CLM51%FATES-NOCOMP_SICE_SOCN_SROF_SGLC_SWAV_SESP.betzy_intel.clm-FatesColdNoCompNoFire

ERS_Ld90.f45_f45_mg37.2000_DATM%GSWP3v1_CLM51%FATES-NOCOMP_SICE_SOCN_SROF_SGLC_SWAV_SESP.betzy_intel.clm-FatesColdNoCompNoFire

However what is interesting is that this test passes restart:
ERS_Ld90.f45_f45_mg37.2000_DATM%GSWP3v1_CLM51%FATES-NOCOMP_SICE_SOCN_SROF_SGLC_SWAV_SESP.betzy_intel.clm-FatesColdNoCompNoFire.20230707_114133_1m5tec/

Since the restart test fails - we cannot really start an longer runs until we resolve this problem.

### PR DESCRIPTION
**Pull request by rgknox**
### Description:

We had been calling a routine (canopy_structure()) during the restart read process. The purpose was to facilitate rebuilding the canopy. However, this had an inadvertent effect of changing results from base, because this procedure would not just rebuild, but modify the cohort compositions due to termination and promotion/demotion in the canopy. We realized that we could simply bypass this call, and add two variables to the restart file to achieve b4b restarts in tests.

This is an API change PR, and needs to be synchronized with https://github.com/ESCOMP/CTSM/pull/2199

Fixes #1051 

### Collaborators:

@mvdebolskiy identified the locus of the problem which enabled its fix, with team contributions and troubleshooting from @mvertens , @glemieux , @rosiealice and @ckoven

### Expectation of Answer Changes:

No answer changes aside from a fixed bug.

### Checklist

*If this is your first time contributing, please read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/main/CONTRIBUTING.md) document.*

All checklist items must be checked to enable merging this pull request:

*Contributor*
- [x] The documentation has been assessed to determine if updates are necessary

*Integrator*
- [ ] FATES PASS/FAIL regression tests were run
- [ ] Evaluation of test results for answer changes was performed and results provided

### Documentation

- [Technical Note](https://github.com/NGEET/fates-docs) update:
- [User's Guide](https://github.com/NGEET/fates-users-guide) update: 

### Test Results:

*CTSM (or) E3SM (specify which) test hash-tag:*

*CTSM (or) E3SM (specify which) baseline hash-tag:*

*FATES baseline hash-tag:*

*Test Output:*

### CODE REVIEW

**Comment by rgknox** [comment]
Update, this set of changes does enable some tests to pass the restart compare test that did not previously (ie ERS 5month f10/f45), however longer ERS tests a la 10 months still do not pass.

**Comment by rosiealice** [comment]
Oh boo. Should we push these changes anyway and start a new line of investigation for the subsequent failure? 

Just checking whether it is nocomp or full fates mode that fails? Or both?

**Comment by mvdebolskiy** [comment]
Can confirm, ERS_Lm11... passes, ERS_Lm13 does not.

**Comment by rosiealice** [comment]
Can you decide those for me @mvdebolskiy ? (Are they both nocomp?)

**Comment by mvdebolskiy** [comment]
@rosiealice both nocomp. Also spitfire mode 0.

**Comment by rgknox** [comment]
All, I've made some more updates.  See comments in https://github.com/NGEET/fates/issues/1051 regarding spread.  I also realized that we had not add the variable that remembers a plants net carbon uptake at the leaf layer, to the restart. This finally adds it (although its a memory hog, but a necessary one right now).
I now have 13 month restart tests passing for full fates with this branch. Please give it a try and stress test it.

File: main/FatesRestartInterfaceMod.F90 [hunk 1]
```diff
@@ -1124,25 +1133,35 @@ subroutine define_restart_vars(this, initialize_variables)
     
     ! Only register satellite phenology related restart variables if it is turned on!
```
Comment (glemieux) [inline main/FatesRestartInterfaceMod.F90:1134]: Minor cleanup; since we use `hlm_use_sp` in a bunch of places still, I think moving this up to be included in a general comment would be ideal.  Or we can strike it altogether since it's not relevant in this specific place in the code anymore.

**Review by glemieux — APPROVED** [review]
One minor area of comment cleanup suggested, but we can also punt on it until later.

File: main/FatesRestartInterfaceMod.F90 (hunk 1 above)
Comment (rgknox) [reply main/FatesRestartInterfaceMod.F90:1134]: discussed with @glemieux will incorporate into future PR

**Comment by glemieux** [comment]
It looks like this fixed #897 and ESCOMP/CTSM#667.
