### PR TITLE
fix calculation of the distance between model grid and inventory sites

### LINKED ISSUE #1457: Potential issue in matching model grids and inventory sites when coordinates in different format
https://github.com/NGEET/fates/blob/1afb393de4c4d3c74c2f95ca714b9f34996abbdf/main/FatesInventoryInitMod.F90#L239-L240

I was running a regional FATES initialization using inventory data from a bunch of different sites. The customized model grids have the longitudes in [-180,180] degree format, which is same as the coordinates formate of the inventory sites. Also, inventory sites were mapped to model grids before hand, thus the latitude and longitude columns in the control file corresponds to exact target model grid, so we would not expect model fail due to model cannot find the closest inventory site within allowed precision. I still run into the issue, which later I discovered that at line 620, model converted negative longitudes of inventory sites to positive, this then made a mismatch between model grids and inventory sites in their coordinates format, and lines 239-240 are fragile to this format mismatch. 

https://github.com/NGEET/fates/blob/1afb393de4c4d3c74c2f95ca714b9f34996abbdf/main/FatesInventoryInitMod.F90#L620

One suggestion to fix this is to change the calculation of the distance between model grid and inventory grid in lines 239-240 to something like: dlon = abs( modulo(site_lon - inv_lon(:) + 180._r8, 360._r8) - 180._r8 ); distance = sqrt((site_lat - inv_lat)**2 + dlon**2). In this way, the calculation of dlon does not depend on exact same format between site and model grid coordinates as it's always computing the circular difference.

### PR DESCRIPTION
**Pull request by XiulinGao**
### Description:

this PR fix #1457 
### Collaborators:

@glemieux @rgknox 

### Expectation of Answer Changes:

Should not expect any change in model results but to fix potential model failure if coords of inventory sites are on different scales from those of model grids
### Checklist

*If this is your first time contributing, please read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/main/CONTRIBUTING.md) document.*

All checklist items must be checked to enable merging this pull request:

*Contributor*
- [x] The in-code documentation has been updated with descriptive comments
- [x] The documentation has been assessed to determine if updates are necessary

*Integrator*
- [x] FATES PASS/FAIL regression tests were run
- [x] Evaluation of test results for answer changes was performed and results provided
- [x] FATES-CLM6 Code Freeze: satellite phenology regression tests are b4b

*If satellite phenology regressions are **not** b4b, please hold merge and notify the FATES development team.*

### Documentation

- [Technical Note](https://github.com/NGEET/fates-docs) update:
- [User's Guide](https://github.com/NGEET/fates-users-guide) update: 

### Test Results:

*CTSM (or) E3SM (specify which) test hash-tag:*

*CTSM (or) E3SM (specify which) baseline hash-tag:*

*FATES baseline hash-tag:*

*Test Output:*

### CODE REVIEW

File: main/FatesInventoryInitMod.F90 [hunk 1]
```diff
@@ -231,13 +233,14 @@ subroutine initialize_sites_by_inventory(nsites,sites,bc_in)
       ! For each site, identify the most proximal PSS/CSS couplet, read-in the data
       ! allocate linked lists and assign to memory
       do s = 1, nsites
-         invsite = &
-               minloc( (sites(s)%lat-inv_lat_list(:))**2.0_r8 + &
-               (sites(s)%lon-inv_lon_list(:))**2.0_r8 , dim=1)
+         delta_lon_list = abs(modulo((sites(s)%lon - inv_lon_list(:)) + &
```
Comment (rgknox) [inline main/FatesInventoryInitMod.F90]: Tempted to create a little unit test for this...

Comment (XiulinGao) [reply main/FatesInventoryInitMod.F90]: @rgknox Go ahead! it's always good to have one.

**Comment by glemieux** [comment]
Regression testing underway on `derecho`.

**Comment by glemieux** [comment]
Regression testing against `fates-sci.1.88.1_api.42.0.0-ctsm5.3.085` is complete.  All results are B4B except for the expected difference in the only other test mode that uses `GreatCircleDist` which is seed dispersal.

Results: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr1475-085`
