### PR TITLE
sci.1.92.4_api.45.0.0: Complete the FATES-CLM nitrogen coupling

### LINKED ISSUE #1454: Add graceful fails to prevent P-coupling with CLM
In FATES we have an option when running in nutrient enabled (ie CNP) mode, that allows the user to prescribe the N or P uptake rates, or accept the uptake rates detrmined by the competition scheme in the land model.  This is controlled in the parameter file, with [fates_cnp_prescribed_nuptake](https://github.com/NGEET/fates/blob/sci.1.86.3_api.40.0.0/parameter_files/fates_params_default.cdl#L222-L224) and [fates_cnp_prescribed_puptake](https://github.com/NGEET/fates/blob/sci.1.86.3_api.40.0.0/parameter_files/fates_params_default.cdl#L222-L224)

Values of 0 signal there should be coupling, where positive values signal there should not be coupling and FATES should generate uptake synthetically.  Why do we have prescribed rates? Firstly, it allows us to test FATES-CNP, by removing variability in coupled uptake. And secondly, it allows us to simulate the limitation of one chemical species instead of both.

In most cases, when using prescribed uptake, the value should be set large, ie 1 or greater, so that chemical species has no chance of limiting the simulation.  Any excess will simply be lost to litter fluxes. 

CLM does not cycle phosphorus, and thus FATES cannot exchange phosphorus with CLM.  So CLM should never be run with P coupling active.

We should add protections in the code, [here](https://github.com/NGEET/fates/blob/sci.1.86.3_api.40.0.0/main/FatesInterfaceMod.F90#L928), so that the model fails if the host model is CLM and p_uptake_mode= coupled_p_uptake.

### PR DESCRIPTION
**Pull request by slevis-lmwg**
### Description:
I started this PR with changes needed in https://github.com/ESCOMP/CTSM/pull/3409.
So far that's just the renaming of
prt_carbon_allom_hyp to fates_c_only 
prt_cnp_flex_allom_hyp to fates_cn

The corresponding ESCOMP issue:
https://github.com/ESCOMP/CTSM/issues/3378

Resolves #1454 
Reminder to address https://github.com/NGEET/fates/issues/1526

### Collaborators:
@rgknox 
@adrifoster 

### Expectation of Answer Changes:
I do not expect answers to change as a result of this PR alone; however, I expect answers to change for `fates_parteh_mode = 2` as a result of the corresponding ESCOMP PR. So far I have not seen such diffs, while I have seen diffs for `fates_parteh_mode = 1`.

### Checklist
All checklist items must be checked to enable merging this pull request:

*Contributor*
- [x] The in-code documentation has been updated with descriptive comments
- [x] The documentation has been assessed to determine if updates are necessary: To be discussed at CTSM Software meeting tomorrow

*Integrator*
- [x] FATES PASS/FAIL regression tests were run
As posted [here](https://github.com/ESCOMP/CTSM/pull/3409#issuecomment-4238969834), and again below I ran the fates test-suite against the corresponding baseline with satisfactory results
- [x] Evaluation of test results for answer changes was performed and results provided
As posted [here](https://github.com/ESCOMP/CTSM/pull/3409#discussion_r3081517093), I identified the lines of code responsible for the answer changes
- [x] FATES-CLM6 Code Freeze: satellite phenology regression tests are b4b
In `/glade/derecho/scratch/slevis/tests_0413-123625de` I invoked `./cs.status.fails | grep -i fatessp` with this result:
```
    FAIL ERI_D_Ld9.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdSatPhenCamLndTuningMode NLCOMP
    FAIL SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdSatPhen NLCOMP
    FAIL SMS_D_Ld3.f09_g17.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdSatPhen_prescribed NLCOMP
    FAIL ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen NLCOMP
    FAIL ERS_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen NLCOMP
    FAIL SMS_Lm1.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdBasic NLCOMP
    FAIL SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen NLCOMP
```

*If satellite phenology regressions are **not** b4b, please hold merge and notify the FATES development team.*

### Documentation

- [Technical Note](https://github.com/NGEET/fates-docs) update:
- [User's Guide](https://github.com/NGEET/fates-users-guide) update: 

### Test Results:

*CTSM (or) E3SM (specify which) test hash-tag:*

*CTSM (or) E3SM (specify which) baseline hash-tag:*

*FATES baseline hash-tag:*

*Test Output:*

### CODE REVIEW

File: biogeochem/EDCohortDynamicsMod.F90 [hunk 1]
```diff
@@ -68,8 +68,8 @@ Module EDCohortDynamicsMod
   use FatesAllometryMod  , only : bstore_allom
   use FatesAllometryMod  , only : ForceDBH
   use FatesAllometryMod    , only : set_root_fraction
-  use PRTGenericMod,          only : prt_carbon_allom_hyp
-  use PRTGenericMod,          only : prt_cnp_flex_allom_hyp
+  use PRTGenericMod,          only : fates_c_only
+  use PRTGenericMod,          only : fates_cn
```
Comment (slevis-lmwg) [inline biogeochem/EDCohortDynamicsMod.F90]: @rgknox you recently brought up the naming choice of the two indices in lines 71-72. I should have named the second one fates_cnp, but I will refrain from making changes until we follow up and agree on something.

File: main/FatesInterfaceMod.F90 [hunk 2]
```diff
@@ -2346,9 +2322,9 @@ subroutine UpdateFatesRMeansTStep(sites,bc_in, bc_out)
            do while (associated(ccohort))
               !   call ccohort%tveg_lpa%UpdateRMean(bc_in(s)%t_veg_pa(ifp))
               if(.not.ccohort%isnew)then
-                 ! [kgC/plant/yr] -> [gC/m2/s]
+                 ! [kgC/plant/yr] -> [gC/m2/yr]
                  site_npp = site_npp + ccohort%npp_acc_hold * ccohort%n*area_inv * &
-                      g_per_kg * hlm_days_per_year / sec_per_day
+                      g_per_kg
```
Comment (slevis-lmwg) [inline main/FatesInterfaceMod.F90:2362]: Effectively the same change as in PR #1513 (commit 8eca6e3e5bdea1c7f8ed4aad3e89f0879098cb30). Update to it when the latter gets merged to main. OR just merge PR #1513.

**Comment by slevis-lmwg** [comment]
Ryan's update today:
"the team agreed at the fates software meeting that "fates_conly" and "fates_cn" were good names for the switch, both in the namelist and for the integer named constants that we pass between files"

File: biogeochem/EDCohortDynamicsMod.F90 (hunk 1 above)
Comment (slevis-lmwg) [reply biogeochem/EDCohortDynamicsMod.F90]: Kept fates_c_only and changed to fates_cnp. I will resolve this conversation.

File: functional_unit_testing/parteh/f90src/FatesCohortWrapMod.F90 [hunk 3]
```diff
@@ -35,8 +35,8 @@ module FatesCohortWrapMod
   use PRTGenericMod,          only : carbon12_element
   use PRTGenericMod,          only : SetState
   use PRTGenericMod,          only : prt_global
-  use PRTGenericMod,          only : prt_carbon_allom_hyp   
-  use PRTGenericMod,          only : prt_cnp_flex_allom_hyp
+  use PRTGenericMod,          only : fates_c_only
+  use PRTGenericMod,          only : fates_cnp
```
Comment (slevis-lmwg) [inline functional_unit_testing/parteh/f90src/FatesCohortWrapMod.F90]: Is this ok, or should it have also been changed to

```suggestion
  use PRTGenericMod,          only : carbon_only
  use PRTGenericMod,          only : carbon_nitrogen_phosphorus
```
and, if so, how did we miss it? Possibly came in with main in the last merge...
- [x] Make sure to change all the instances in this file. 
- [x] Oh, this is in "functional_unit_testing" so I guess it does not affect tests from the fates test-suite!

Comment (rgknox) [reply functional_unit_testing/parteh/f90src/FatesCohortWrapMod.F90]: This is functional unit testing code, so not in the typical pipeline of testing. But yes, good catch!

**Comment by slevis-lmwg** [comment]
@glemieux I just added you as the reviewer also on the FATES side. This is the FATES-CN PR that we talked about this morning.

**Review by glemieux — APPROVED** [review]

**Comment by slevis-lmwg** [comment]
@glemieux I'm not certain whether it's ok for me to check the unchecked boxes at the top and merge this, or whether I should wait for you or @rgknox to do it.

**Comment by slevis-lmwg** [comment]
I reviewed and checked all remaining checkboxes, and I have permission to merge. I will ask at tomorrow's CTSM Software meeting whether it's ok for me to merge and tag this PR.

**Comment by slevis-lmwg** [comment]
- [x] I will rerun the fates test-suite to generate a new baseline
- [x] I will meet with @glemieux to discuss the merge steps

**Comment by slevis-lmwg** [comment]
- [x] derecho: `./run_sys_tests -s fates -c fates-sci.1.92.2_api.44.1.0-ctsm5.4.033 -g fates-sci.1.92.3_api.44.1.1-ctsm5.4.036`
- [x] izumi in progress: `./run_sys_tests -s fates -c fates-sci.1.92.1_api.44.1.0-ctsm5.4.034 -g fates-sci.1.92.4_api.45.0.0-ctsm5.4.036 --skip-git-status`
- [x] When done, rename the izumi baseline to `fates-sci.1.92.4_api.45.0.0-ctsm5.4.036`
- [x] Merge and tag `sci.1.92.4_api.45.0.0`

**Comment by slevis-lmwg** [comment]
Tagged as follows:
```
git tag -a sci.1.92.4_api.45.0.0
git push origin sci.1.92.4_api.45.0.0
```

**Comment by glemieux** [comment]
HLM-FATES compatibility table updated: https://github.com/NGEET/fates-users-guide/pull/115
